---
- name: Configure RHEL 9 utils node
  hosts: all
  become: true

  tasks:

    - name: Enable SSH password authentication
      ansible.builtin.replace:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication no'
        replace: 'PasswordAuthentication yes'
      notify: Restart sshd

    - name: Create 'devops' user with password
      ansible.builtin.user:
        name: devops
        state: present
        password: "{{ 'devops' | password_hash('sha512') }}"

    - name: Allow 'devops' user to execute sudo without a password
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/devops
        line: "devops ALL=(ALL) NOPASSWD: ALL"
        create: true
        mode: '0440'

    - name: Add host SSH public key to devops authorized_keys
      ansible.posix.authorized_key:
        user: devops
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

  handlers:
    - name: Restart sshd
      ansible.builtin.systemd:
        name: sshd
        state: restarted
