---
- name: Wordpress | Apache | Copy virtual host configuration file
  template:
    src: apache-vhost.conf.j2
    dest: "/etc/apache2/sites-available/{{ wp_sitename }}.conf"
    owner: root
    group: root
    mode: 0644

- name: WordPress | Apache | Enable site
  command: "sudo a2ensite {{ wp_sitename }}.conf"
