---
# cofigure kubernetes nodes with users and access

- hosts: all
  become: true
  vars_files:
  vars:
    remote_user_name: devops
    # remote_user_public_key_file: '~/.ssh/id_rsa.pub'
    # #remote_user_public_key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDPCgWXeSm2t9XJrvCMPMpr0TmhOvnS0e0kax05EeSLXTc98dv4ewP+9Mvc2Vl+2LifAK/FXZlpzexQugnHJ8oUbfjxiD0ZEQQhpV1pLkHp4zDyl4p+fneMtahCYhqkI0YPpN/RCGTxrWxppc65NXaHOGvt9O7bKJCQyR0LvUHbXUw4dqgd5OB2FxL6h0hbe4XxFgJ3Cl7GlSDe3ly14Tdh4ZdvqDxAbtGly1q9HHInWhBxFOpIFrKmN7d6+NhiJK0i5/a8MMmAaGvI0x5pSmM5Ehg+sns11gnt8tvt8MLdHI2SuTiBDLepkgF5CPc2lScH/lkiUbmvqIVKYlddhuKR devops@vm-towernode-10.lab.local'
    # remote_user_public_key: "{{lookup('file', remote_user_public_key_file )}}"

  tasks:
    - name: Create new user on managed node
      user:
        name: "{{ remote_user_name }}"
        groups: wheel
        append: yes

    # - name: Add key to managed node
    #   authorized_key:
    #     user: "{{ remote_user_name }}"
    #     key: "{{ remote_user_public_key }}"
    #     manage_dir: yes

    - name: Add sudo entries for new user
      copy:
        content: "{{ remote_user_name }} ALL=(ALL) NOPASSWD: ALL"
        dest: "/etc/sudoers.d/{{ remote_user_name }}"

    - name: Configure Hostname
      hostname:
        name: "{{ inventory_hostname }}"