- name: Add an apt signing key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add apt repository for stable version
  apt_repository:
    # repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present
- name: Update system
  shell: sudo apt update -y