- name: Install packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - curl
    - containerd.io

- name: Configure containerd
  shell: "{{ item }}"
  with_items:
    - 'mkdir -p /etc/containerd'
    - 'containerd config default>/etc/containerd/config.toml'
    # - 'sudo systemctl restart containerd'

- name: Ensure SystemdCgroup is set to true
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: ^SystemdCgroup =*
    line: 'SystemdCgroup = true'

- name: Restart containerd service
  ansible.builtin.service:
    name: containerd
    state: restarted

# - name: Install docker and its dependecies
#   apt: 
#     name: "{{ packages }}"
#     state: present
#     update_cache: yes
#   vars:
#     packages:
#     # - docker-ce 
#     # - docker-ce-cli 
#     - containerd.io
#   notify:
#     - docker status

  # - name: Add vagrant user to docker group
  #   user:
  #     name: vagrant
  #     group: docker
