IMAGE_NAME = "generic/ubuntu2104"
VM_NAME = "Generic-Ubuntu21"
NODES = 1

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    (1..NODES).each do |i|
        config.vm.define "#{VM_NAME}-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            #node.vm.network "private_network", ip: "192.168.50.#{i + 20}", virtualbox__intnet: "intnet"

            ## add a host-only adaptor. 
            ## Change this line as needed if your host-only network name is different :name => 'vboxnet0', , adapter : 2
            node.vm.network "private_network", type: "dhcp"
            node.vm.hostname = "#{VM_NAME}-#{i}"

            # VM customization
            node.vm.provider :virtualbox do |vb|
                vb.name = "#{VM_NAME}-#{i}"
                vb.memory = 1024
                vb.cpus = 1
            end

            # provisioning
            # adding host ssh key for direct ssh login
            node.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "host_ssh_public_key"
            node.vm.provision "shell", inline: <<-SHELL
                cat host_ssh_public_key >> /home/vagrant/.ssh/authorized_keys
            SHELL
        end
    end
        
end