IMAGE_NAME = "debian/buster64"
NODE_NAME = "wp-101"

Vagrant.configure("2") do |config|
    #config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
    end

    config.ssh.insert_key = true
    config.ssh.forward_agent = true

    config.vm.network "forwarded_port",
    guest: 80,
    host:  8080,
    auto_correct: true

    config.vm.network "forwarded_port",
    guest: 443,
    host:  8443,
    auto_correct: true

    config.vm.define NODE_NAME do |wpnode|

        wpnode.vm.box = IMAGE_NAME
        # wpnode.vm.network "private_network", ip: "192.168.50.10"
        wpnode.vm.hostname = NODE_NAME

        # naming the virtualmachine
        wpnode.vm.provider :virtualbox do |vb|
            vb.name = NODE_NAME
        end
        #wpnode.vm.provision "ansible_local" do |ansible|
        #    ansible.compatibility_mode = "2.0"
        #    ansible.playbook = "install-minikube.yaml"
        #    ansible.extra_vars = {
        #        node_ip: "192.168.50.10",
        #    }
        #end
    end
end