IMAGE_NAME = "generic/rhel8"
VM_CONTROLLER_NAME = "AnsibleController1x"
VM_DBNODE_NAME = "AAP-DB"
VM_AAP_HUB_NAME = "AutomationHub"
NODES = 1
DBNODES = 2

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    (1..NODES).each do |i|
        config.vm.define "#{VM_CONTROLLER_NAME}-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            #node.vm.network "private_network", ip: "192.168.50.#{i + 20}", virtualbox__intnet: "intnet"
            node.vm.network "private_network", type: "dhcp", 
                name: 'vboxnet12', adapter: 2
            node.vm.hostname = "#{VM_CONTROLLER_NAME}-#{i}"

            # VM customization
            node.vm.provider :virtualbox do |vb|
                vb.name = "#{VM_CONTROLLER_NAME}-#{i}"
                vb.memory = 4096
                vb.cpus = 2
                vb.customize ["modifyvm", :id, "--groups", "/mygroupname"]
            end
            #--------------- provisioning ---------------
            # adding host ssh key for direct ssh login
            node.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "host_ssh_public_key"
            node.vm.provision "shell", inline: <<-SHELL
                cat host_ssh_public_key >> /home/vagrant/.ssh/authorized_keys
            SHELL
            
            node.vm.provision "ansible" do |ansible|
                ansible.compatibility_mode = "2.0"
                ansible.playbook = "files/engine-config.yaml"
                #ansible.extra_vars = {
                #    node_ip: "192.168.100.10",
                #}
            end
        end
    end

    ##============ DB NODES============
    (1..DBNODES).each do |i|
        config.vm.define "#{VM_DBNODE_NAME}-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            #node.vm.network "private_network", ip: "192.168.50.#{i + 20}", virtualbox__intnet: "intnet"
            node.vm.network "private_network", type: "dhcp", 
                name: 'vboxnet12', adapter: 2
            node.vm.hostname = "#{VM_DBNODE_NAME}-#{i}"

            # VM customization
            node.vm.provider :virtualbox do |vb|
                vb.name = "#{VM_DBNODE_NAME}-#{i}"
                vb.memory = 4096
                vb.cpus = 2
                vb.customize ["modifyvm", :id, "--groups", "/mygroupname"]
            end
            #--------------- provisioning ---------------
            # adding host ssh key for direct ssh login
            node.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "host_ssh_public_key"
            node.vm.provision "shell", inline: <<-SHELL
                cat host_ssh_public_key >> /home/vagrant/.ssh/authorized_keys
            SHELL
            
            node.vm.provision "ansible" do |ansible|
                ansible.compatibility_mode = "2.0"
                ansible.playbook = "files/engine-config.yaml"
            end
        end
    end

    #(1..NODES).each do |i|
    #    config.vm.define "#{VM_AAP_HUB_NAME}-#{i}" do |node|
    #        node.vm.box = IMAGE_NAME
    #        #node.vm.network "private_network", ip: "192.168.50.#{i + 20}", virtualbox__intnet: "intnet"
    #        node.vm.hostname = "#{VM_AAP_HUB_NAME}-#{i}"
#
    #        # VM customization
    #        node.vm.provider :virtualbox do |vb|
    #            vb.name = "#{VM_AAP_HUB_NAME}-#{i}"
    #            vb.memory = 4096
    #            vb.cpus = 2
    #        end
    #    end
    #end
        
end