IMAGE_NAME = "generic/rhel9"
VM_NAME = "aap25-rhel92"
NODES = 1

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    (1..NODES).each do |i|
        config.vm.define "#{VM_NAME}-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.57.122"

            # set hostname
            node.vm.hostname = "#{VM_NAME}-#{i}"

            # VM customization
            node.vm.provider :virtualbox do |vb|
                vb.name = "#{VM_NAME}-#{i}"
                vb.memory = 512
                vb.cpus = 1
            end

            # provisioning
            # adding host ssh key for direct ssh login
            node.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "host_ssh_public_key"
            node.vm.provision "shell", inline: <<-SHELL
                cat host_ssh_public_key >> /home/vagrant/.ssh/authorized_keys
            SHELL
            node.vm.provision "ansible" do |ansible|
                ansible.compatibility_mode = "2.0"
                ansible.playbook = "files/config.yaml"
            end
        end
    end

end