IMAGE_NAME = "generic/rhel9"
VM_NAME = "aap-rhel-92"
NODES = 1

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    (1..NODES).each do |i|
        config.vm.define "#{VM_NAME}-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            #node.vm.network "private_network", ip: "192.168.50.#{i + 20}", virtualbox__intnet: "intnet"

            ## add a host-only adaptor. 
            ## Change this line as needed if your host-only network name is different :name => 'vboxnet0', , adapter : 2
            #node.vm.network "private_network", type: "dhcp", 
            #    name: 'vboxnet12', adapter: 2
            # adding hostonly network 
            # node.vm.network "private_network", type: "dhcp",    netmask: "255.255.255.0", dhcp_ip:"192.168.57.2", dhcp_lower: "192.168.57.100", :dhcp_upper=>"192.168.57.254"

                         #type: "dhcp", 
            # adding hostonly network 
            # node.vm.network "private_network", type: "dhcp", netmask: "255.255.255.0", dhcp_ip:"192.168.57.2", dhcp_lower: "192.168.57.100", :dhcp_upper=>"192.168.57.254"
            # node.vm.network "private_network", type: "dhcp"
                # ip: "192.168.57.91"
                # type: "dhcp",
                #name: 'vboxnet0'
                
                #name: 'vboxnet0',
                #type: "dhcp"
                #adapter: 2
                
                #ip: "192.168.56.102"
            
                # set hostname
            node.vm.hostname = "#{VM_NAME}-#{i}"

            # VM customization
            node.vm.provider :virtualbox do |vb|
                vb.name = "#{VM_NAME}-#{i}"
                vb.memory = 512
                vb.cpus = 1
                #vb.gui = true
            end

            # provisioning
            # adding host ssh key for direct ssh login
            node.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "host_ssh_public_key"
            node.vm.provision "shell", inline: <<-SHELL
                cat host_ssh_public_key >> /home/vagrant/.ssh/authorized_keys
            SHELL
            node.vm.provision "ansible" do |ansible|
                # ansible.compatibility_mode = "2.0"
                ansible.playbook = "files/config.yaml"
            end
        end
    end
        
end