---
galaxy_info:
  role_name: wordpress
  author: matteocastagnaro
  description: WordPress with webserver (Nginx or Apache2)
  company: "makarenalabs.com"
  license: "license (BSD, MIT)"
  min_ansible_version: 1.4
  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - disco
    - name: Debian
      versions:
        - stretch
        - buster
  galaxy_tags:
    - development
    - web
